### PR TITLE
Update firebase-perf to 20.1.1 and remove firebase.core requirement (Android)

### PR DESCRIPTION
**Pull request by jordanbisato**
[firebase.performance-android-2.1.2.zip](https://github.com/hansemannn/titanium-firebase-performance/files/9735979/firebase.performance-android-2.1.2.zip)

### CODE REVIEW

**Comment by hansemannn** [comment]
Thanks for the PR! Can you please also bump the manifest version and attach the new binary? Thank you!

**Comment by jordanbisato** [comment]
Done!

**Review by hansemannn — APPROVED** [review]
Great work, thank you!

**Comment by jordanbisato** [comment]
@hansemannn can you add the topic "hacktoberfest" to yours firebase project repos? Thanks!

**Comment by m1ga** [comment]
you can also add the label `hacktoberfest-accepted` to this PR

**Comment by jordanbisato** [comment]
I don't have the permission to do this on this repository.

**Comment by m1ga** [comment]
sorry, meant Hans. But I just saw that I can do it too :-)

**Pull request merged**
